name: pythia-tutorial-dev
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- myst-nb
- pandas
- pip
- pyyaml
- pre-commit
- cffconvert
- pip:
  - git+https://github.com/ProjectPythia/sphinx-pythia-theme.git@theme-update
