name: deploy-site

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-site.yaml
    with:
      environment_name: pythia-tutorial-dev
      environment_file: environment.yml
      path_to_source: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Download Artifact Site
        uses: actions/download-artifact@v3
        with:
          name: site-zip-${{ github.event.number }}

      - name: Unzip the site
        run: |
          rm -rf site/_build/html
          unzip site.zip
          rm -f site.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/_build/html
          keep_files: true  # This preserves existing previews from open PRs
