name: trigger-site-build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: .github/workflows/build-site.yaml
    with:
      environment_name: pythia-tutorial-dev
      environment_file: environment.yml
      path_to_source: ./site
      use_cached_environment: 'true'  # This is default, not strickly needed. Set to 'false' to always build a new environment
