name: trigger-site-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_file: 'environment.yml'
      environment_name: pythia-tutorial-dev
      artifact_name: book-zip-${{ github.event.number }}
      path_to_notebooks: 'site'
      build_command: 'make -j4 html'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml